[package]
name = "tracing-tree"
version = "0.1.0"
authors = ["David Barsky <me@davidbarsky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.11"
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing" }
quanta = "0.3.1"
termcolor = "1.0.5"
