[package]
name = "tracing-tree"
version = "0.1.0"
authors = ["David Barsky <me@davidbarsky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.12"
tracing-subscriber = "0.2.0-alpha.5"
quanta = "0.3.1"
termcolor = "1.0.5"
ansi_term = "0.12.1"
chrono = "0.4.10"
